name: Publish

on:
  push:
    tags:
      - 'v*'
# on:
#   workflow_run:
#     workflows: [Run Tests]
#     types:
#       - completed

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release Asset
    runs-on: ubuntu-20.04 # glibc 2.31
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install
        
      - name: Build project
        run: yarn build
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: | 
            bundles/@yarnpkg/plugin-fuse.js
            fuse/output/*

  test-published:
    if: startsWith(github.ref, 'refs/tags/')
    depends-on: publish
    name: Test published 
    runs-on: ubuntu-20.04 # glibc 2.31
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable Corepack
        run: corepack enable

      - name: Test
        run: yarn run test-deployed
        env:
          FUSE_PLUGIN_PATH: ${{ steps.create_release.outputs.url }}/plugin-fuse.js
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: | 
            bundles/@yarnpkg/plugin-fuse.js
            fuse/output/*
